services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    user: debian
    cap_add:
      - PERFMON
      - SYS_PTRACE
      - IPC_LOCK
      - SYSLOG
